#ifndef VIPP4_TEST_MPI_VI_H
#define VIPP4_TEST_MPI_VI_H
#include "mm_comm_vi.h"
ERRORTYPE AW_MPI_VI_GetFrame(VI_DEV, VI_CHN, VIDEO_FRAME_INFO_S *, int);
ERRORTYPE AW_MPI_VI_ReleaseFrame(VI_DEV, VI_CHN, VIDEO_FRAME_INFO_S *);
ERRORTYPE AW_MPI_VI_CreateVipp(VI_DEV);
ERRORTYPE AW_MPI_VI_DestroyVipp(VI_DEV);
ERRORTYPE AW_MPI_VI_EnableVipp(VI_DEV);
ERRORTYPE AW_MPI_VI_DisableVipp(VI_DEV);
ERRORTYPE AW_MPI_VI_SetVippAttr(VI_DEV, VI_ATTR_S *);
ERRORTYPE AW_MPI_VI_CreateVirChn(VI_DEV, VI_CHN, void *);
ERRORTYPE AW_MPI_VI_DestroyVirChn(VI_DEV, VI_CHN);
ERRORTYPE AW_MPI_VI_EnableVirChn(VI_DEV, VI_CHN);
ERRORTYPE AW_MPI_VI_DisableVirChn(VI_DEV, VI_CHN);
#endif
